### ISSUE TITLE
Todo Friday before release

### ISSUE THREAD

**Issue by Hendrik1704** [smash-transport/sparkx#99]
-  [ ] #97 List types in Oscar / Jetscape
-  [x] #98 SigmaGen in Jetscape
-  [x] #18 Flow test class: GenerateFlow -> on branch `roch/GenerateFlow`
-  [x] #87 Requirements (Niklas)
-  [x] Finalize flow classes + documentation (ChatGPT) 
-  [ ] #96 Time step read in (after #97) + #14
-  [x] Switch to SMASH collaboration (with Alessandro), what happens with our actions??
-  [x] Tag version 1.0.0
-  [ ] Prepare GitHub actions for automatic upload to pypi (needs pypi account)

**Comment by NGoetz** [comment]
The day is over.
